#  _____ _           ____      _     _  #
# |_   _| |__   ___ / ___|_ __(_) __| | #
#   | | | '_ \ / _ \ |  _| '__| |/ _` | #
#   | | | | | |  __/ |_| | |  | | (_| | #
#   |_| |_| |_|\___|\____|_|  |_|\__,_| #
#                                       #
#########################################
 
####################
# Tutorial Effects #
###################
# This setting will blind players in the Tutorial.
doTutorialPotionEffects: true
 
###################
# MOTD Management #
###################
# Modify the server's MOTD from TheGrid
overrideMOTD: true
 
# The MOTD to use
motd: "&8-[ &a&lTheGrid &8]-"