name: TheGrid
version: 0.4.0_b1
main: tech.xfyrewolfx.thegrid.TheGrid
Author: xFyreWolfx
softdepend: [MultiWorld, Multiverse-Core]
commands:
  thegrid:
  gridspawn:
permissions:
  thegrid.admin:
    default: op
  thegrid.spawn:
    default: true