name: TheGrid
version: 0.4.0_b2
main: tech.xfyrewolfx.thegrid.TheGrid
Author: xFyreWolfx
softdepend: [MultiWorld, Multiverse-Core]
commands:
  thegrid:
    aliases: grid
  gridspawn:
    aliases: gs
permissions:
  thegrid.admin:
    default: op
  thegrid.spawn:
    default: true