name: The Grid
version: 0.3.0
main: tech.xfyrewolfx.thegrid.Main
Author: xFyreWolfx
commands:
  spawn:
  addsystem:
  addoutlet:
  removesystem:
  shop:
  ?:
  help:
  pl:
  plugins:
  setspawn:
  settutorial:
  reloadmotd: